--- 
title: "Yelp Analysis"
author: "Jie Mei, Liuxin Chen, Ningxin Li, Yihui Hu"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

Yelp is an American public company headquartered in San Francisco, California. It is also the most famous mobile app, which contains basic information, ratings, pictures, order service, comments, etc. for shops mostly in US, Canada and Mexico.

In 2020, due to the epidemic, the opening and closing times, delivery services, and availability of reservation for many restaurants have all changed. We hope to build a platform to facilitate users to have an overall understanding of the restaurant situation in the United States, especially New York, and hope to get some insights during the data processing.

While our platform mainly displays geographic data, it also combines some charts to provide users with more detailed information.

Here are what you can get from our platform.
1. Geographical distribution of yelp restaurants in USA filtered by different categories.
2. Covid information of yelp restaurants.
3. Ratings distribution of yelp restaurants in USA.

